name: SYNC_REPO_EVERYDAY

on:
  schedule:
    - cron:  '0 1 * * *'
  push:
    branches:
      - main

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: douglaskastle/github-sync@master
      with:
        source_repo: "madawei2699/bmpi.dev"
        destination_repo: "bmpi-dev/bmpi.dev"
        source_branch: "master"
        destination_branch: "master"
        github_token: ${{ secrets.PAT }}
        password: ${{ secrets.PAT }}
